using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

namespace CalcDNA.Generator.Tests;

public class CalcWrapperGeneratorTests
{
    #region Helper Methods

    private static async Task VerifyGeneratorAsync(string source, params (string filename, string content)[] expected)
    {
        var test = new CSharpSourceGeneratorTest<CalcWrapperGenerator, DefaultVerifier>
        {
            TestState =
            {
                Sources = { source },
                ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
                AdditionalReferences =
                {
                    MetadataReference.CreateFromFile(typeof(CalcDNA.Attributes.CalcAddInAttribute).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(CalcDNA.Runtime.UnoMarshal).Assembly.Location),
                }
            }
        };

        foreach (var (filename, content) in expected)
        {
            test.TestState.GeneratedSources.Add((typeof(CalcWrapperGenerator), filename, content));
        }

        await test.RunAsync();
    }

    private static Task VerifyNoGenerationAsync(string source)
    {
        return VerifyGeneratorAsync(source);
    }

    #endregion

    #region Basic Generation Tests

    [Fact]
    public async Task Generator_WithSimpleMethod_GeneratesWrapper()
    {
        const string source = """
            using CalcDNA.Attributes;

            namespace TestNamespace
            {
                [CalcAddIn]
                public static partial class TestFunctions
                {
                    [CalcFunction]
                    public static double Add(double a, double b)
                    {
                        return a + b;
                    }
                }
            }
            """;

        // Use explicit \r\n for Windows line endings to match generated output
        var expected =
            "// <auto-generated/>\r\n" +
            "#nullable enable\r\n" +
            "using System;\r\n" +
            "using CalcDNA.Runtime;\r\n" +
            "\r\n" +
            "namespace TestNamespace\r\n" +
            "{\r\n" +
            "    public partial class TestFunctions\r\n" +
            "    {\r\n" +
            "        public static double Add_UNOWrapper(double a, double b)\r\n" +
            "        {\r\n" +
            "            try\r\n" +
            "            {\r\n" +
            "                return Add(a, b);\r\n" +
            "            }\r\n" +
            "            catch (Exception ex)\r\n" +
            "            {\r\n" +
            "                throw new Exception($\"Error calling Add: \" + ex.Message);\r\n" +
            "            }\r\n" +
            "        }\r\n" +
            "    }\r\n" +
            "}";

        await VerifyGeneratorAsync(source, ("TestFunctions_Add_Wrapper.g.cs", expected));
    }

    #endregion

    #region No Generation Tests

    [Fact]
    public async Task Generator_WithoutCalcAddIn_DoesNotGenerate()
    {
        const string source = """
            using CalcDNA.Attributes;

            namespace TestNamespace
            {
                // Missing [CalcAddIn] attribute
                public static partial class TestFunctions
                {
                    [CalcFunction]
                    public static double Add(double a, double b)
                    {
                        return a + b;
                    }
                }
            }
            """;

        await VerifyNoGenerationAsync(source);
    }

    [Fact]
    public async Task Generator_WithoutCalcFunction_DoesNotGenerate()
    {
        const string source = """
            using CalcDNA.Attributes;

            namespace TestNamespace
            {
                [CalcAddIn]
                public static partial class TestFunctions
                {
                    // Missing [CalcFunction] attribute
                    public static double Add(double a, double b)
                    {
                        return a + b;
                    }
                }
            }
            """;

        await VerifyNoGenerationAsync(source);
    }

    [Fact]
    public async Task Generator_WithNonStaticClass_DoesNotGenerate()
    {
        const string source = """
            using CalcDNA.Attributes;

            namespace TestNamespace
            {
                [CalcAddIn]
                public partial class TestFunctions // Not static
                {
                    [CalcFunction]
                    public static double Add(double a, double b)
                    {
                        return a + b;
                    }
                }
            }
            """;

        await VerifyNoGenerationAsync(source);
    }

    [Fact]
    public async Task Generator_WithNonStaticMethod_DoesNotGenerate()
    {
        // Note: Instance methods require non-static class
        const string source = """
            using CalcDNA.Attributes;

            namespace TestNamespace
            {
                [CalcAddIn]
                public partial class TestFunctions // Not static - allows instance methods
                {
                    [CalcFunction]
                    public double Add(double a, double b) // Not static
                    {
                        return a + b;
                    }
                }
            }
            """;

        await VerifyNoGenerationAsync(source);
    }

    #endregion
}
