using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;

namespace CalcDNA.CLI;

/// <summary>
/// Generates a Python UNO service script that bridges to .NET via pythonnet.
/// Each [CalcAddIn] class becomes a Python UNO service class. The script bootstraps
/// pythonnet, loads the add-in DLL, and delegates function calls to the generated
/// _PyWrapper methods on the C# classes.
///
/// LO discovers the Python component via the manifest entry:
///   application/vnd.sun.star.uno-component;type=Python
/// LO's pythonloader loads the module and uses g_ImplementationHelper to register
/// the service factories. State persists for the process lifetime (module cached).
/// </summary>
internal static class PythonUnoServiceGenerator
{
    /// <summary>
    /// Builds the Python UNO service script content.
    /// </summary>
    /// <param name="addinName">Sanitized add-in name (used for class prefixes and impl names)</param>
    /// <param name="assemblyFileName">Main add-in DLL filename including extension</param>
    /// <param name="addInClasses">Discovered [CalcAddIn] classes with their [CalcFunction] methods</param>
    /// <param name="logger">Logger instance</param>
    /// <returns>Python script content as string</returns>
    public static string BuildPythonScript(string addinName, string assemblyFileName,
        IEnumerable<AddInClass> addInClasses, Logger logger)
    {
        var sb = new StringBuilder();
        var classes = addInClasses.ToList();

        // Header and stdlib imports
        sb.AppendLine("# <auto-generated by CalcDNA — do not edit>");
        sb.AppendLine("import uno");
        sb.AppendLine("import unohelper");
        sb.AppendLine("import os");
        sb.AppendLine();

        // pythonnet bootstrap: resolve DLLs relative to this script
        sb.AppendLine("import clr");
        sb.AppendLine("_dir = os.path.dirname(os.path.abspath(__file__))");
        sb.AppendLine($"clr.AddReference(os.path.join(_dir, \"CalcDNA.Runtime.dll\"))");
        sb.AppendLine($"clr.AddReference(os.path.join(_dir, \"{assemblyFileName}\"))");
        sb.AppendLine();

        // Import .NET add-in classes via pythonnet
        foreach (var addIn in classes)
        {
            var ns = addIn.Type.Namespace;
            var className = addIn.Type.Name;
            if (string.IsNullOrEmpty(ns))
                sb.AppendLine($"import {className}");
            else
                sb.AppendLine($"from {ns} import {className}");
            logger.Debug($"  Python import: {(string.IsNullOrEmpty(ns) ? className : $"{ns}.{className}")}", true);
        }
        sb.AppendLine();

        // Generate one UNO service class per AddInClass
        foreach (var addIn in classes)
        {
            GenerateServiceClass(sb, addinName, addIn, logger);
        }

        // Register all implementations with UNO via g_ImplementationHelper.
        // pythonloader looks for this module-level variable to obtain the component factory.
        sb.AppendLine("g_ImplementationHelper = unohelper.ImplementationHelper()");
        foreach (var addIn in classes)
        {
            var className = addIn.Type.Name;
            var pyClassName = $"{addinName}_{className}";
            var implName = $"{addinName}.{className}";
            sb.AppendLine("g_ImplementationHelper.addImplementation(");
            sb.AppendLine($"    {pyClassName},");
            sb.AppendLine($"    \"{implName}\",");
            sb.AppendLine($"    (\"{implName}\", \"com.sun.star.sheet.AddIn\"),");
            sb.AppendLine(")");
        }

        return sb.ToString();
    }

    private static void GenerateServiceClass(StringBuilder sb, string addinName, AddInClass addIn, Logger logger)
    {
        var className = addIn.Type.Name;
        var pyClassName = $"{addinName}_{className}";

        sb.AppendLine($"class {pyClassName}(unohelper.Base):");
        sb.AppendLine($"    \"\"\"UNO add-in service wrapping {className}.\"\"\"");
        sb.AppendLine();
        sb.AppendLine("    def __init__(self, ctx):");
        sb.AppendLine("        self.ctx = ctx");
        sb.AppendLine();

        // XLocalizable.setLocale — required by XAddIn
        sb.AppendLine("    def setLocale(self, language, country):");
        sb.AppendLine("        pass");
        sb.AppendLine();

        foreach (var method in addIn.Methods)
        {
            GenerateMethodWrapper(sb, className, method);
            logger.Debug($"  Python wrapper: {className}.{method.Name}", true);
        }
    }

    private static void GenerateMethodWrapper(StringBuilder sb, string className, MethodInfo method)
    {
        var methodName = method.Name;
        var paramNames = method.GetParameters()
            .Select(p => p.Name ?? $"arg{p.Position}")
            .ToList();

        string signature = paramNames.Count > 0
            ? "self, " + string.Join(", ", paramNames)
            : "self";

        sb.AppendLine($"    def {methodName}({signature}):");
        sb.AppendLine($"        return {className}.{methodName}_PyWrapper({string.Join(", ", paramNames)})");
        sb.AppendLine();
    }
}
